## Predicción para el precio de importación de pesticidas en Colombia

El sector agrícola ha experimentado un incremento permanente en los precios al consumidor durante los últimos años. Esto puede ser asociado a varios factores, pero el que vale la pena mencionar en esta parte del desarrollo del proyecto es el incremento en el valor en la tasa de cambio y su impacto en la fluctuación del precio de los insumos importados. El sector agrícola depende de pesticidas importados para su producción, y el comportamiento en los últimos años en el precio de la tasa representativa del mercado (TRM), ha encarecido la compra de estos bienes. Un ejemplo de cómo afecta esta situación al sector agrícola se ve reflejado en un informe de Fedepapa donde se afirma que el alza de    todos los insumos importados llevó a que la producción de una hectárea de papa en noviembre del 2022 llegara a costar $34 millones mientras que en el 2021 tenía un valor de $22 millones de pesos 

## Formulación del problema
¿Como pronosticar un precio promedio de los pesticidas seleccionados, a partir de las técnicas y herramientas que ofrece las ciencias de datos?

## La ciencia de Datos (DS)
En un entorno tan competitivo como el que se enfrenta en la actualidad, las organizaciones, gremios e instituciones de cualquier tipo requieren de estrategias innovadoras para poder adaptarse a los fuertes cambios del presente y obtener fuertes conocimientos a partir de los datos e información disponible, es una muy buena estrategia para poder tomar decisiones pertinentes y administrar estos conjuntos de datos potencialmente invaluables.
Se puede definir la DS, como la aplicación de métodos cualitativos y cuantitativos para predecir resultados y solucionar problemas relevantes que atiendan a la creciente e inmensa cantidad de datos que existe actualmente y que se tienen disponibles. En la actualidad hay muchos algoritmos para el procesamiento y extracción de datos, DS proporciona a los profesionales una estructura y un conjunto de principios que dan un marco para tratar sistemáticamente los problemas de extracción de conocimiento útil de los datos [6]. A continuación, se abordará una breve definición de los principales principios de DS que se consideran relevantes para poder desarrollar la propuesta de este proyecto.
Para efectos de este proyecto, se propone utilizar algunas de las herramientas más de la DS, para así poder encontrar un modelo tal que estime el precio de un bien, para este caso algunos de los pesticidas importados en Colombia, que facilite la toma de decisiones en el sector agrícola y transcienda en el mercado internacional. 
