
## Los Datos
Los datos se encuentran alojados en la página de la Dian. Estas bases estadísticas de Comercio Exterior comprenden el movimiento legal de mercancías que ingresan o salen del territorio aduanero nacional -TAN- a través de las diferentes aduanas del país, desde o hacia otros países y zonas francas del territorio nacional; a esta información se le ha aplicado filtros, ajustes estadísticos y lineamientos metodológicos estadísticos nacionales e internacionales, respecto de las operaciones de Comercio Exterior de Bienes, dando cumplimiento a los principios de transparencia y acceso a la información pública, sin perjuicio del cumplimiento de las normas vigentes en materia de protección de datos personales, los Principios Fundamentales de las Estadísticas Oficiales de las Naciones Unidas y el Código Nacional de Buenas Prácticas del Sistema Estadístico Nacional del Departamento Administrativo Nacional de Estadística -DANE. (Nacionales, s.f.)
Este conjunto de datos se extrajo y se estructuró únicamente con las partidas arancelarias que hacen parte de los pesticidas que se modelarán.

## Creación del Dataset

Una vez que los datos fueron extraídos, se procedió a la creación del conjunto de datos. Esto implicó organizar la información en un formato estructurado que fuera adecuado para su posterior análisis. Se asignaron etiquetas y se verificó la coherencia de los datos para garantizar su calidad.
En este punto se realizó ajuste a las variables determinando las que mayor información generan para el análisis que se espera y dejando las de la información de nombres de importador y exportador, departamentos de destino, el peso neto, valor de la transacción de dólares, la descripción de la mercancía, la tasa de cambio, así como la fecha de presentación y partiendo de estos datos base, se crea la variable valor por kilo en la que se divide el valor FOB de la transacción sobre el peso que indica la importación tratando de definir para cada entrada al país de mercancía el valor de cada Kilo. 
Se agrega adicional la descripción de la partida arancelaria indicando las que son Insecticidas, herbicidas y fungicidas para el análisis posterior. 

## Limpieza de los Datos
En esta fase, se llevó a cabo un proceso exhaustivo de limpieza de los datos. Se identificaron y corrigieron posibles errores, valores atípicos y datos faltantes. Además, se aplicaron técnicas de normalización y estandarización para asegurar la consistencia y la fiabilidad de los datos.
En este punto se realiza la homologación de los importadores que en el análisis resultan ser los de mayor importancia y más volumen de importaciones generan ya que en algunos casos están escritos de manera diferente haciendo referencia a la misma empresa y en otros, por investigación de estas empresas, logramos determinar que hasta determinado año tenían una razón social diferente. Más adelante describiremos estas uniones y compras de compañías que hacen dinámico el mercado general de los pesticidas en Colombia. 

Se obtuvo un Dataset robusto con 60.401 observaciones y 11 variables a partir de la minería de los datos, se realizaron algunos cálculos referentes al proceso exploratorio de los datos logrando encontrar correlaciones y consiguiendo identificar patrones entre las variables para corregir problemas de sesgo.
